stages:
    - build
    - test

variables:
    test: "IDesign.Regonizers.Tests"

before_script:
    - "cd IDesign"
    - "dotnet restore"

build:
    stage: build
    script:
        - "dotnet build"
    only:
        - master
        - develop
        - merge_requests

test:
    stage: test
    script: 
        - "cd $test"
        - "dotnet test"
    only:
        - master
        - develop
        - merge_requests