image: microsoft/dotnet:latest

stages:
    - build
    - test

variables:
    test: "Test-Analyzer/Test_Analyzer.Test"

before_script:
    - "dotnet restore"
    - "dotnet sln Test-Analyzer.sln remove Test-Analyzer/Test_Analyzer.Vsix/Test_Analyzer.Vsix.csproj"

build:
    stage: build
    script:
        - "dotnet build Test-Analyzer.sln"

test:
    stage: test
    script: 
        - "cd $test"
        - "dotnet test"