image: microsoft/dotnet:latest

stages:
    - build
    - test

variables:
    test: "Test-Analyzer/Test_Analyzer.Test"

before_script:
    - "dotnet restore"

build:
    stage: build
    script:
        - "dotnet build"
    only:
        - master
        - develop
        - merge_requests

test:
    stage: test
    script: 
        - "dotnet test"
    only:
        - master
        - develop
        - merge_requests