stages:
    - build
    - test

variables:
    test: "IDesign.Regonizers.Tests"

before_script:
    - "dotnet restore"

build:
    stage: build
    script:
        - "cd IDesign"
        - "dotnet build"
    only:
        - master
        - develop
        - merge_requests

test:
    stage: test
    script: 
        - "cd IDesign"
        - "dotnet Ibuild"
        - "cd ..\\"
        - "call .\test_script.bat" 
    only:
        - master
        - develop
        - merge_requests
    artifacts:
        paths:
            - coverage.xml