// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PatternPal.Extension
{
    internal sealed partial class Vsix
    {
        public const string Id = "PatternPal.Extension";
        public const string Name = "PatternPal.Extension";
        public const string Description = @"A Design Pattern recognition tool.";
        public const string Language = "en-US";
        public const string Version = "3.6.0";
        public const string Author = "Team PatternPal";
        public const string Tags = "";
    }
}
