//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ClassFeedbackRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClassFeedbackRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommonResources.ClassFeedbackRes", typeof(ClassFeedbackRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adaptee should Extends an the adapter.
        /// </summary>
        public static string AdapteeExtendsApter {
            get {
                return ResourceManager.GetString("AdapteeExtendsApter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter Field should have adaptee as type.
        /// </summary>
        public static string AdapteeField {
            get {
                return ResourceManager.GetString("AdapteeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adaptee should be  used by adapter.
        /// </summary>
        public static string AdapteeIsUsed {
            get {
                return ResourceManager.GetString("AdapteeIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has adaptee.
        /// </summary>
        public static string AdapterAdaptee {
            get {
                return ResourceManager.GetString("AdapterAdaptee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class adapter.
        /// </summary>
        public static string AdapterClass {
            get {
                return ResourceManager.GetString("AdapterClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Adapter methods should call adaptee.
        /// </summary>
        public static string AdapterMethod {
            get {
                return ResourceManager.GetString("AdapterMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter method should override or is ipmlemented.
        /// </summary>
        public static string AdapterMethodOverride {
            get {
                return ResourceManager.GetString("AdapterMethodOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter method should return adaptee.
        /// </summary>
        public static string AdapterMethodReturnType {
            get {
                return ResourceManager.GetString("AdapterMethodReturnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter method uses adpatee.
        /// </summary>
        public static string AdapterMethodUses {
            get {
                return ResourceManager.GetString("AdapterMethodUses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter should be extended by or implemented by.
        /// </summary>
        public static string AdapterParent {
            get {
                return ResourceManager.GetString("AdapterParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decorator component.
        /// </summary>
        public static string DecoratorComponent {
            get {
                return ResourceManager.GetString("DecoratorComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decorator component should be implemented or extended by one other class.
        /// </summary>
        public static string DecoratorComponentChilDecoratorComponentChild {
            get {
                return ResourceManager.GetString("DecoratorComponentChilDecoratorComponentChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decorator component field should be {0}.
        /// </summary>
        public static string DecoratorComponentFieldType {
            get {
                return ResourceManager.GetString("DecoratorComponentFieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decorator component should have at least one method.
        /// </summary>
        public static string DecoratorComponentMethodAny {
            get {
                return ResourceManager.GetString("DecoratorComponentMethodAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decorator component should method should be public or protected.
        /// </summary>
        public static string DecoratorComponentMethodModifier {
            get {
                return ResourceManager.GetString("DecoratorComponentMethodModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decorator component method should have a parameter with type {0}.
        /// </summary>
        public static string DecoratorComponentMethodParameters {
            get {
                return ResourceManager.GetString("DecoratorComponentMethodParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concrete decorator.
        /// </summary>
        public static string DecoratorConcrete {
            get {
                return ResourceManager.GetString("DecoratorConcrete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concrete decorator method should use {0} and call its base.
        /// </summary>
        public static string DecoratorConcreteMethodArguments {
            get {
                return ResourceManager.GetString("DecoratorConcreteMethodArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concrete decorator method should be public.
        /// </summary>
        public static string DecoratorConcreteMethodModifier {
            get {
                return ResourceManager.GetString("DecoratorConcreteMethodModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concrete decorator method should have a parameter with type {0}.
        /// </summary>
        public static string DecoratorConcreteMethodParameters {
            get {
                return ResourceManager.GetString("DecoratorConcreteMethodParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decorator should be extended by a class.
        /// </summary>
        public static string DecoratorNodeChild {
            get {
                return ResourceManager.GetString("DecoratorNodeChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decorator should be abstract..
        /// </summary>
        public static string DecoratorNodeModifier {
            get {
                return ResourceManager.GetString("DecoratorNodeModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decorator should extend or implement a class.
        /// </summary>
        public static string DecoratorNodeParent {
            get {
                return ResourceManager.GetString("DecoratorNodeParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object adapter.
        /// </summary>
        public static string ObjectAdapter {
            get {
                return ResourceManager.GetString("ObjectAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private constructor.
        /// </summary>
        public static string SingletonConstructor {
            get {
                return ResourceManager.GetString("SingletonConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singleton constructor should not be public..
        /// </summary>
        public static string SingletonConstructorModifier {
            get {
                return ResourceManager.GetString("SingletonConstructorModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has instance of itself.
        /// </summary>
        public static string SingletonField {
            get {
                return ResourceManager.GetString("SingletonField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singleton field should not be public..
        /// </summary>
        public static string SingletonFieldModifierPriv1ate {
            get {
                return ResourceManager.GetString("SingletonFieldModifierPriv1ate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singleton field should not be public..
        /// </summary>
        public static string SingletonFieldModifierPrivate {
            get {
                return ResourceManager.GetString("SingletonFieldModifierPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singleton field should be static..
        /// </summary>
        public static string SingletonFieldModifierStatic {
            get {
                return ResourceManager.GetString("SingletonFieldModifierStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singleton field type should be {0}..
        /// </summary>
        public static string SingletonFieldType {
            get {
                return ResourceManager.GetString("SingletonFieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has GetInstance().
        /// </summary>
        public static string SingletonMethod {
            get {
                return ResourceManager.GetString("SingletonMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singleton method should be public..
        /// </summary>
        public static string SingletonMethodModifier {
            get {
                return ResourceManager.GetString("SingletonMethodModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singleton method should be able to return a new Singleton..
        /// </summary>
        public static string SingletonMethodReturnCreationType {
            get {
                return ResourceManager.GetString("SingletonMethodReturnCreationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singleton method  shoudl return itself..
        /// </summary>
        public static string SingletonMethodReturnType {
            get {
                return ResourceManager.GetString("SingletonMethodReturnType", resourceCulture);
            }
        }
    }
}
