//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDesign.CommonResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ClassFeedbackRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClassFeedbackRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IDesign.CommonResources.ClassFeedbackRes", typeof(ClassFeedbackRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adaptee should Extends an the adapter.
        /// </summary>
        public static string AdapteeExtendsApter {
            get {
                return ResourceManager.GetString("AdapteeExtendsApter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter Field should have adaptee as type.
        /// </summary>
        public static string AdapteeField {
            get {
                return ResourceManager.GetString("AdapteeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adaptee should be  used by adapter.
        /// </summary>
        public static string AdapteeIsUsed {
            get {
                return ResourceManager.GetString("AdapteeIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has adaptee.
        /// </summary>
        public static string AdapterAdaptee {
            get {
                return ResourceManager.GetString("AdapterAdaptee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class adapter.
        /// </summary>
        public static string AdapterClass {
            get {
                return ResourceManager.GetString("AdapterClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Adapter methods should call adaptee..
        /// </summary>
        public static string AdapterMethod {
            get {
                return ResourceManager.GetString("AdapterMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter method should return adaptee..
        /// </summary>
        public static string AdapterMethodReturnType {
            get {
                return ResourceManager.GetString("AdapterMethodReturnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter method uses adpatee..
        /// </summary>
        public static string AdapterMethodUses {
            get {
                return ResourceManager.GetString("AdapterMethodUses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should be extended by a class..
        /// </summary>
        public static string Child {
            get {
                return ResourceManager.GetString("Child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concrete decorator constructor.
        /// </summary>
        public static string ConcreteDecoratorConstructor {
            get {
                return ResourceManager.GetString("ConcreteDecoratorConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method should have the component as a parameter..
        /// </summary>
        public static string ConcreteDecoratorMethodParameters {
            get {
                return ResourceManager.GetString("ConcreteDecoratorMethodParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructor should not be public..
        /// </summary>
        public static string ConstructorModifierNotPublic {
            get {
                return ResourceManager.GetString("ConstructorModifierNotPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decorator.
        /// </summary>
        public static string Decorator {
            get {
                return ResourceManager.GetString("Decorator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decorator component.
        /// </summary>
        public static string DecoratorComponent {
            get {
                return ResourceManager.GetString("DecoratorComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should be implemented or extended by one other class..
        /// </summary>
        public static string DecoratorComponentChild {
            get {
                return ResourceManager.GetString("DecoratorComponentChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decorator component constructor.
        /// </summary>
        public static string DecoratorComponentConstructor {
            get {
                return ResourceManager.GetString("DecoratorComponentConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decorator component field.
        /// </summary>
        public static string DecoratorComponentField {
            get {
                return ResourceManager.GetString("DecoratorComponentField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field should be the component..
        /// </summary>
        public static string DecoratorComponentFieldType {
            get {
                return ResourceManager.GetString("DecoratorComponentFieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method should have the component as a parameter..
        /// </summary>
        public static string DecoratorComponentMethodParameters {
            get {
                return ResourceManager.GetString("DecoratorComponentMethodParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concrete decorator.
        /// </summary>
        public static string DecoratorConcrete {
            get {
                return ResourceManager.GetString("DecoratorConcrete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concrete decorator method should use the component and call its base..
        /// </summary>
        public static string DecoratorConcreteMethodArguments {
            get {
                return ResourceManager.GetString("DecoratorConcreteMethodArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstract Creator.
        /// </summary>
        public static string FactoryAbstractCreator {
            get {
                return ResourceManager.GetString("FactoryAbstractCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create method.
        /// </summary>
        public static string FactoryAbstractCreatorMethod {
            get {
                return ResourceManager.GetString("FactoryAbstractCreatorMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concrete creator.
        /// </summary>
        public static string FactoryConcreteCreator {
            get {
                return ResourceManager.GetString("FactoryConcreteCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create method of the concrete creator.
        /// </summary>
        public static string FactoryConcreteCreatorMethod {
            get {
                return ResourceManager.GetString("FactoryConcreteCreatorMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concrete creator should have at least one method..
        /// </summary>
        public static string FactoryConcreteCreatorMethodAny {
            get {
                return ResourceManager.GetString("FactoryConcreteCreatorMethodAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concrete product should have at least one method.
        /// </summary>
        public static string FactoryConcreteProductMethodAny {
            get {
                return ResourceManager.GetString("FactoryConcreteProductMethodAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product of the factory method.
        /// </summary>
        public static string FactoryCreates {
            get {
                return ResourceManager.GetString("FactoryCreates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method should create a product..
        /// </summary>
        public static string FactoryMethodCreateTypeProduct {
            get {
                return ResourceManager.GetString("FactoryMethodCreateTypeProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method should return a product..
        /// </summary>
        public static string FactoryMethodReturnTypeProduct {
            get {
                return ResourceManager.GetString("FactoryMethodReturnTypeProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method should return a product interface..
        /// </summary>
        public static string FactoryMethodReturnTypeProductInterface {
            get {
                return ResourceManager.GetString("FactoryMethodReturnTypeProductInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field should not be public..
        /// </summary>
        public static string FieldModifierNotPublic {
            get {
                return ResourceManager.GetString("FieldModifierNotPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field should be private..
        /// </summary>
        public static string FieldModifierPrivate {
            get {
                return ResourceManager.GetString("FieldModifierPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field should be static..
        /// </summary>
        public static string FieldModifierStatic {
            get {
                return ResourceManager.GetString("FieldModifierStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field type should be {0}..
        /// </summary>
        public static string FieldType {
            get {
                return ResourceManager.GetString("FieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There should be atleast 3 methods: add, remove and notify..
        /// </summary>
        public static string MethodAmountThree {
            get {
                return ResourceManager.GetString("MethodAmountThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should have at least one method..
        /// </summary>
        public static string MethodAny {
            get {
                return ResourceManager.GetString("MethodAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method body should be empty..
        /// </summary>
        public static string MethodBodyEmpty {
            get {
                return ResourceManager.GetString("MethodBodyEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method should create an interface of this class but not this class itself..
        /// </summary>
        public static string MethodCreateSameInterface {
            get {
                return ResourceManager.GetString("MethodCreateSameInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method should create {0}..
        /// </summary>
        public static string MethodCreateType {
            get {
                return ResourceManager.GetString("MethodCreateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method should be abstract..
        /// </summary>
        public static string MethodModifierAbstract {
            get {
                return ResourceManager.GetString("MethodModifierAbstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method should not be private..
        /// </summary>
        public static string MethodModifierNotPrivate {
            get {
                return ResourceManager.GetString("MethodModifierNotPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method should be public..
        /// </summary>
        public static string MethodModifierPublic {
            get {
                return ResourceManager.GetString("MethodModifierPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method should be static..
        /// </summary>
        public static string MethodModifierStatic {
            get {
                return ResourceManager.GetString("MethodModifierStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method should override or is implemented..
        /// </summary>
        public static string MethodOverride {
            get {
                return ResourceManager.GetString("MethodOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class should have no methods with this parameter type {0}..
        /// </summary>
        public static string MethodParameterNone {
            get {
                return ResourceManager.GetString("MethodParameterNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method should have a parameter with type {0}..
        /// </summary>
        public static string MethodParameters {
            get {
                return ResourceManager.GetString("MethodParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method should return {0}..
        /// </summary>
        public static string MethodReturnType {
            get {
                return ResourceManager.GetString("MethodReturnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class should be abstract or an interface..
        /// </summary>
        public static string NodeAbstractOrInterface {
            get {
                return ResourceManager.GetString("NodeAbstractOrInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node should not make other classes..
        /// </summary>
        public static string NodeDoesNotCreate {
            get {
                return ResourceManager.GetString("NodeDoesNotCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node should not use other classes..
        /// </summary>
        public static string NodeDoesNotUse {
            get {
                return ResourceManager.GetString("NodeDoesNotUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should be implemented by a class..
        /// </summary>
        public static string NodeImplementedByAny {
            get {
                return ResourceManager.GetString("NodeImplementedByAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class should be abstract..
        /// </summary>
        public static string NodeModifierAbstract {
            get {
                return ResourceManager.GetString("NodeModifierAbstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should not implement an interface..
        /// </summary>
        public static string NodeNotImplementedAny {
            get {
                return ResourceManager.GetString("NodeNotImplementedAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should be a class..
        /// </summary>
        public static string NodeTypeClass {
            get {
                return ResourceManager.GetString("NodeTypeClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This class should be used by other classes..
        /// </summary>
        public static string NodeUsedByAny {
            get {
                return ResourceManager.GetString("NodeUsedByAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node must have atleast 1 uses relation..
        /// </summary>
        public static string NodeUses1 {
            get {
                return ResourceManager.GetString("NodeUses1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object adapter.
        /// </summary>
        public static string ObjectAdapter {
            get {
                return ResourceManager.GetString("ObjectAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observer.
        /// </summary>
        public static string Observer {
            get {
                return ResourceManager.GetString("Observer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observer concrete subject.
        /// </summary>
        public static string ObserverConcreteSubject {
            get {
                return ResourceManager.GetString("ObserverConcreteSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observer concrete subject field.
        /// </summary>
        public static string ObserverConcreteSubjectField {
            get {
                return ResourceManager.GetString("ObserverConcreteSubjectField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There should be 2 methods which both have one of the same parameters {0}..
        /// </summary>
        public static string ObserverMethodParameters {
            get {
                return ResourceManager.GetString("ObserverMethodParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject interface.
        /// </summary>
        public static string ObserverSubjectInterface {
            get {
                return ResourceManager.GetString("ObserverSubjectInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should be extended by or implemented by a class..
        /// </summary>
        public static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should be product class..
        /// </summary>
        public static string ProductClass {
            get {
                return ResourceManager.GetString("ProductClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private constructor.
        /// </summary>
        public static string SingletonConstructor {
            get {
                return ResourceManager.GetString("SingletonConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has instance of itself.
        /// </summary>
        public static string SingletonField {
            get {
                return ResourceManager.GetString("SingletonField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singleton field type should be {0}..
        /// </summary>
        public static string SingletonFieldType {
            get {
                return ResourceManager.GetString("SingletonFieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has GetInstance().
        /// </summary>
        public static string SingletonMethod {
            get {
                return ResourceManager.GetString("SingletonMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singleton method should be able to return a new Singleton..
        /// </summary>
        public static string SingletonMethodReturnCreationType {
            get {
                return ResourceManager.GetString("SingletonMethodReturnCreationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singleton method  should return itself..
        /// </summary>
        public static string SingletonMethodReturnType {
            get {
                return ResourceManager.GetString("SingletonMethodReturnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent class or interface of the concrete state class.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change state method in concrete state class.
        /// </summary>
        public static string StateClassChangeState {
            get {
                return ResourceManager.GetString("StateClassChangeState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State concrete class.
        /// </summary>
        public static string StateConcrete {
            get {
                return ResourceManager.GetString("StateConcrete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State context class.
        /// </summary>
        public static string StateContext {
            get {
                return ResourceManager.GetString("StateContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State context field.
        /// </summary>
        public static string StateContextField {
            get {
                return ResourceManager.GetString("StateContextField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concrete state class creates another state.
        /// </summary>
        public static string StateCreatesOtherState {
            get {
                return ResourceManager.GetString("StateCreatesOtherState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used return type.
        /// </summary>
        public static string StateFieldStateType {
            get {
                return ResourceManager.GetString("StateFieldStateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change state method.
        /// </summary>
        public static string StateNodeMethods {
            get {
                return ResourceManager.GetString("StateNodeMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent class or interface of the concrete strategy class.
        /// </summary>
        public static string Strategy {
            get {
                return ResourceManager.GetString("Strategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concrete strategy class.
        /// </summary>
        public static string StrategyConcrete {
            get {
                return ResourceManager.GetString("StrategyConcrete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concrete strategy method.
        /// </summary>
        public static string StrategyConcreteMethod {
            get {
                return ResourceManager.GetString("StrategyConcreteMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy context class.
        /// </summary>
        public static string StrategyContext {
            get {
                return ResourceManager.GetString("StrategyContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy context field.
        /// </summary>
        public static string StrategyContextField {
            get {
                return ResourceManager.GetString("StrategyContextField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used return type.
        /// </summary>
        public static string StrategyFieldStateType {
            get {
                return ResourceManager.GetString("StrategyFieldStateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy method.
        /// </summary>
        public static string StrategyNodeMethods {
            get {
                return ResourceManager.GetString("StrategyNodeMethods", resourceCulture);
            }
        }
    }
}
