//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDesign.Extension.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SummaryRescources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SummaryRescources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IDesign.Extension.Resources.SummaryRescources", typeof(SummaryRescources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to But {0} mostly looks like the {1} pattern..
        /// </summary>
        internal static string ClassScoresHighestOn {
            get {
                return ResourceManager.GetString("ClassScoresHighestOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • &apos;{0}&apos; seems part of the {1} pattern..
        /// </summary>
        internal static string ClassSeemsPartOf {
            get {
                return ResourceManager.GetString("ClassSeemsPartOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} classes and/or interfaces were analysed.
        /// </summary>
        internal static string MultipleEntiyNodesAnalysed {
            get {
                return ResourceManager.GetString("MultipleEntiyNodesAnalysed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From {0} files.
        /// </summary>
        internal static string MultipleFiles {
            get {
                return ResourceManager.GetString("MultipleFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} patterns are recognized:.
        /// </summary>
        internal static string MultiplePatternsRecognized {
            get {
                return ResourceManager.GetString("MultiplePatternsRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No patterns were recognized..
        /// </summary>
        internal static string NoPatternsRecognized {
            get {
                return ResourceManager.GetString("NoPatternsRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No classes were found for analysis.
        /// </summary>
        internal static string NothingClassesOrInterfacesFound {
            get {
                return ResourceManager.GetString("NothingClassesOrInterfacesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one class or interface has been analysed..
        /// </summary>
        internal static string OneEntityNodeAnalysed {
            get {
                return ResourceManager.GetString("OneEntityNodeAnalysed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From this file.
        /// </summary>
        internal static string OneFile {
            get {
                return ResourceManager.GetString("OneFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One pattern is recognized:.
        /// </summary>
        internal static string OnePatternRecognized {
            get {
                return ResourceManager.GetString("OnePatternRecognized", resourceCulture);
            }
        }
    }
}
