name: Build

on:
  push:
    branches:
      - master
      - develop
    paths:
      - 'PatternPal/**'
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - 'PatternPal/**'
  workflow_dispatch:
    
jobs:
  Build:
    runs-on: windows-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1
        with:
          msbuild-architecture: x64
           
      - name: Restore NuGet Packages
        run: nuget restore PatternPal/PatternPal.sln
        
      - name: Build
        run: msbuild /p:Configuration=Release PatternPal/PatternPal.sln
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: PatternPal
          path: ./PatternPal/PatternPal.Extension/bin/Release/PatternPal.Extension.vsix
