name: Build

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  should_build:
    outputs:
      status: ${{ steps.has-changes.conclusion }}
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: tj-actions/changed-files@v35
        id: changed-files
        with:
          files: PatternPal/**
      - name: Check for changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        id: has-changes
        run: echo PatternPal has changed files
    
  Build_Logserver:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false && needs.should_build.outputs.status == 'success'
    steps:
      - uses: actions/checkout@v3
      - name: Set up docker BuildX
        uses: docker/setup-buildx-action@v2.5.0
      - name: Build the Docker image
        uses: docker/build-push-action@v4
        with:
          context: PatternPal/
          file: PatternPal/PatternPal.LoggingServer/Dockerfile

  Build:
    runs-on: windows-latest
    if: github.event.pull_request.draft == false && needs.should_build.outputs.status == 'success'
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1
        with:
          msbuild-architecture: x64

      - name: Restore NuGet Packages
        run: nuget restore PatternPal/PatternPal.sln

      - name: Build
        run: msbuild /p:Configuration=Release PatternPal/PatternPal.sln

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: PatternPal
          path: ./PatternPal/PatternPal.Extension/bin/Release/PatternPal.Extension.vsix
