name: ReSharper

on:
  push:
    branches:
      - master
      - develop
    paths:
      - 'PatternPal/**'
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - 'PatternPal/**'
  workflow_dispatch:

jobs:
  resharper:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: resharper
        uses: ovda96/resharper-action@master
        with:
          solution: PatternPal/PatternPal.sln
