name: Lint

on:
  workflow_call:
    inputs:
      should_run:
        required: true
        type: true
  workflow_dispatch:

jobs:
  inspection:
    runs-on: windows-latest
    if: inputs.should_run
    name: Inspection
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Remove extension from solution
        run: dotnet sln PatternPal/PatternPal.sln remove PatternPal/PatternPal.Extension/PatternPal.Extension.csproj

      - name: Inspect code
        uses: muno92/resharper_inspectcode@main
        with:
          workingDirectory: PatternPal
          solutionPath: ./PatternPal.sln
          minimumSeverity: error
