name: ReSharper

on:
  push:
    branches:
      - master
      - develop
    paths:
      - 'PatternPal/**'
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - 'PatternPal/**'
  workflow_dispatch:

jobs:
  inspection:
    runs-on: windows-latest #ubuntu-latest # or macos-latest, windows-latest
    name: Inspection
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x' # [3.1.x, 5.0.x, 6.0.x, 7.0.x]
          
      - name: Restore
        run: nuget restore PatternPal/PatternPal.sln
        
      - name: Inspect code
        uses: muno92/resharper_inspectcode@1.6.5
        with:
          solutionPath: PatternPal/PatternPal.sln
