name: Lint

on:
  push:
    branches:
      - master
      - develop
    paths:
      - 'PatternPal/**'
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
    paths:
      - 'PatternPal/**'
  workflow_dispatch:

jobs:
  inspection:
    runs-on: windows-latest #windows-latest, ubuntu-latest, macos-latest
    if: github.event.pull_request.draft == false
    name: Inspection
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Restore cached nuget packages
        uses: actions/cache/restore@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
            
#       - name: Setup .NET
#         uses: actions/setup-dotnet@v3
#         with:
#           dotnet-version: '7.0.x' # [3.1.x, 5.0.x, 6.0.x, 7.0.x]
          
#       - name: Restore packages
#         run: nuget restore PatternPal/PatternPal.sln
        
#       - name: Save nuget packages
#         uses: actions/cache/save@v3
#         with:
#           path: ~/.nuget/packages
#           key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
#           restore-keys: |
#             ${{ runner.os }}-nuget-
        
      - name: Inspect code
        uses: muno92/resharper_inspectcode@main
        with:
          workingDirectory: PatternPal
          solutionPath: ./PatternPal.sln
