name: Release PatternPal.LoggingServer
on:
  push:
    branches:
      - master
  workflow_dispatch:

defaults:
  run:
    working-directory: ./PatternPal

jobs:
  release-logging-server-docker-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - id: patternpal_version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}
          excludes: prerelease, draft
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: PatternPal/
          file: PatternPal/PatternPal.LoggingServer/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/patternpalloggingserver:latest,${{ secrets.DOCKERHUB_USERNAME }}/patternpalloggingserver:${{ steps.patternpal_version.outputs.release }}
