name: Test

on:
  push:
    branches:
      - master
      - develop
    paths:
      - 'PatternPal/**'
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - 'PatternPal/**'

defaults:
  run:
    working-directory: ./PatternPal

jobs:
  test:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Remove extension
        run: dotnet sln PatternPal.sln remove PatternPal.Extension/PatternPal.Extension.csproj
      - uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget
      - name: Restore dependencies
        run: dotnet restore & nuget restore
      - name: Build
        run: dotnet build
      - name: Test
        run: dotnet test --no-build --verbosity normal
