name: Test

on:
  push:
    branches:
      - master
      - develop
    paths:
      - 'PatternPal/**'
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - 'PatternPal/**'
  workflow_dispatch:
    
jobs:
  Build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/cache@v3
        with:
          path: ./PatternPal/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1
        with:
          msbuild-architecture: x64

      - name: Remove extension
        run: dotnet sln PatternPal/PatternPal.sln remove PatternPal/PatternPal.Extension/PatternPal.Extension.csproj
           
      - name: Restore NuGet Packages
        run: nuget restore PatternPal/PatternPal.sln
        
      - name: Build
        run: msbuild /p:Configuration=Release PatternPal/PatternPal.sln
      
  Test:
    runs-on: windows-latest
    needs: Build
    steps:
      - name: Test
        run: dotnet test .\PatternPal\PatternPal.sln --no-build --verbosity normal
