name: Test

on:
  workflow_call:
    inputs:
      should_run:
        required: true
        type: boolean
  workflow_dispatch:

jobs:
  Test:
    runs-on: windows-latest
    if: inputs.should_run
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1
        with:
          msbuild-architecture: x64

      - name: Remove extension
        run: dotnet sln PatternPal/PatternPal.sln remove PatternPal/PatternPal.Extension/PatternPal.Extension.csproj

      - name: Restore NuGet Packages
        run: nuget restore PatternPal/PatternPal.sln

      - name: Build
        run: msbuild PatternPal/PatternPal.sln

      - name: Test
        run: dotnet test --no-build --verbosity normal PatternPal/PatternPal.sln
