// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PatternPal.LoggingServer.Data;

#nullable disable

namespace PatternPal.LoggingServer.Migrations
{
    [DbContext(typeof(ProgSnap2ContextClass))]
    partial class ProgSnap2ContextClassModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PatternPal.LoggingServer.Models.ProgSnap2Event", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ClientDatetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CodeStateId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodeStateSection")
                        .HasColumnType("text");

                    b.Property<string>("CompileMessage")
                        .HasColumnType("text");

                    b.Property<string>("CompileMessageType")
                        .HasColumnType("text");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<int?>("ExecutionResult")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProjectId")
                        .HasColumnType("text");

                    b.Property<string>("RecognizerConfig")
                        .HasColumnType("text");

                    b.Property<string>("RecognizerResult")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ServerDatetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceLocation")
                        .HasColumnType("text");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("ToolInstances")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EventId");

                    b.ToTable("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
